spring:
  application:
    name: auth-server
  datasource:
    druid:
      db-type: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/integrated_oauth?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: root
      password: password
  flyway:
    baseline-on-migrate: true
    baseline-description: <<Flyway Baseline>>
    enabled: true
    check-location: true
    locations: classpath:db/migration
    validate-on-migrate: true
