server:
  port: 8070
  servlet:
    session:
      cookie:
        name: CLIENT-SESSION

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oidc_login?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: <<root>> # update username
    password: <<password>> # update password
  flyway:
    baseline-on-migrate: true
    baseline-description: <<Flyway Baseline>>
    enabled: true
    check-location: true
    locations: classpath:db/migration
    validate-on-migrate: true
